# Generated by Django 5.1.4 on 2025-11-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_category_category_image_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_guest_order',
            field=models.BooleanField(default=False),
        ),
    ]
